[project]
name = "entropic-instruction-following"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.2",
    "nltk>=3.9.2",
    "omegaconf>=2.3.0",
]
