defaults:
  - _self_
  - model: google-gemma-3-270m-it.yaml         # Default to mistral.yaml
  - strategy: standard      # Default to standard.yaml

experiment:
  rule_counts: [50, 100, 200, 400, 800] # todo: move this to data gen
  rule_counts_test: [200]
  trials_per_count: 3
  dataset_path: "data/raw/dataset_v1.json"
  results_dir: "data/results"

word_data_generator:
  seeds: ["food.n.02", "artifact.n.01"]  # List of WordNet synset seeds
  alphanumeric_only: true
  
# These can be overridden by the specific model yamls
inference:
  trust_remote_code: false
  max_model_len: null
  sampling:
    temperature: 0
    top_p: 1.0
    max_tokens: null